### ISSUE TITLE
Обновление версий библиотек

### ISSUE THREAD

**Issue by kompolom** [bem/bem-components-php#1]
Думаю неплохо бы синхронизовать версии с `bem-components`. 
Готов посодействовать этому процессу, но нужно небольшое руководство как это лучше организовать.

**Comment by qfox** [comment]
It's not really hard. We have tmpl specs in bem-components (the only thing we need actually), so we just need to update version in bower.js and then just make patches for templates. Voila!

**Comment by qfox** [comment]
Всмысле, эта штука базируется на bem-core-php и тестах из bem-components, и кроме них ничего не нужно. Надо просто обновить версии и сделать патчи. При запуске npm test все должно быть зеленым — значит шаблоны собираются верно, и все ок ;-)

**Comment by qfox** [comment]
Вообще, сам я планировал этим заняться где-то через неделю-полторы, пока беда со временем. Если запилишь — будет оч круто, по ощущениям там может быть проблема только с шаблонами меню и кнопок внутри. Оч долго с ними маялся и в первый раз, и когда к релизу 2.5 актуализировал. ;-(

**Comment by qfox** [comment]
Обновил. Работы на 20 минут ;-( кто бы знал...

**Comment by un1ko85** [comment]
Супер!!!
