### ISSUE TITLE
select__button выкидывает notice

### ISSUE THREAD

**Issue by kompolom** [bem/bem-components-php#4]
[Тут](https://github.com/bem/bem-components-php/blob/master/common.blocks/select/__button/select__button.bh.php#L5) $mods оказывается не объектом.

**Comment by kompolom** [comment]
Возможно проблема не в шаблоне, а в bh.php

**Comment by kompolom** [comment]
@zxqfox Я PR прислал, но он что то не отображается в списке. Проблема с bh.php в v4.0 Там `blockMods` заменено на `mods`. С bh.js не сравнивал, думаю, ты сам в курсе.

**Comment by qfox** [comment]
@kompolom извини, что долго молчал). Разобрались: https://github.com/bem/bem-components/issues/1587

Надо чинить ;-)

**Comment by qfox** [comment]
@kompolom в bh.js та же самая проблема. Даже не знаю, ждать ли, что решат с фиксом в bh.js шаблонов. Может сделаем фикс, в пхп как-то более критично проблема стоит, имхо. Хотя, я не знаю как там пользователи bh4.0 живут, знать бы этих рисковых парней.

**Comment by un1ko85** [comment]
Живем, и ждем:)

**Comment by kompolom** [comment]
@zxqfox Я пользуюсь 4.0

**Comment by qfox** [comment]
@kompolom в bem-components тот же баг.
