### ISSUE TITLE
select exception

### ISSUE THREAD

**Issue by kompolom** [bem/bem-components-php#6]
select с группами выбрасывает exception 
`Only variables should be passed by reference`

**Comment by kompolom** [comment]
@zxqfox  запилил PR #7 Посмотри пож.

**Comment by qfox** [comment]
These d@gs are slower than issets. What you think about rewriting this code at all? ;-D

**Comment by kompolom** [comment]
Ok. Wait for new PR ))

**Comment by qfox** [comment]
Great, thanks!

**Comment by kompolom** [comment]
@zxqfox Ready!

**Comment by kompolom** [comment]
@zxqfox ping

**Comment by qfox** [comment]
@kompolom All is fine with your code, just can you try to switch travis to php version?

**Comment by kompolom** [comment]
@zxqfox I never use travis, so, I dont know now do it.

**Comment by qfox** [comment]
@kompolom Thanks! [v2.3.1](https://github.com/bem/bem-components-php/releases/tag/v2.3.1) released
